spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/sellfinity
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always